#!/bin/bash

# Ensure pkexec is available
if ! command -v pkexec &>/dev/null; then
    echo "Error: pkexec is not installed. Please install PolicyKit."
    exit 1
fi

# Check if running as root
if [ $EUID -ne 0 ]; then
    exec pkexec /usr/lib/snigdhaos/pkexec-gui "$@"
    exit 1
fi

# Need some previous vars
# shellcheck disable=SC2163
while IFS= read -rd '' var; do export "$var"; done < <(grep --null-data -ae "^\($XDG_CURRENT_DESKTOP\|WAYLAND_DISPLAY\|XDG_RUNTIME_DIR\|XDG_SESSION_TYPE\|XCURSOR_SIZE\|LC_*\|LANG\|LANGUAGE\|QT_WAYLAND_FORCE_DPI\|QT_QPA_PLATFORMTHEME\|QT_STYLE-OVERRIDE\|\)=.*\$" /proc/$PPID/environ)

# If on Wayland, adjust WAYLAND_DISPLAY variable
if [[ -v WAYLAND_DISPLAY ]]; then
    export WAYLAND_DISPLAY="$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY"
fi

# Set root's runtime directory
export XDG_RUNTIME_DIR="/run/user/0"

# Execute the provided command with root privileges
exec "$@"
