#!/bin/bash
set -e

LAUNCH_TERMINAL_SHELL=bash

usage(){
    echo "Usage: ${0##*/} [cmd]"
    echo " -s [shell]    changes the shell to [shell]"
    echo ' -h This help'
    exit 1
}

opts='s:h'

while getopts "${opts}" arg; do
    case "${arg}" in
    s) LAUNCH_TERMINAL_SHELL="$OPTARGS" ;;
    h | ?) usage 0 ;;
    *)
        echo "Invalid arguments '${arg}'"
        usage 1 ;;
    esac
done

shift $((OPTIND - 1))

initfile="$(mktemp)"
codefile="$initfile"
echo "#!/usr/bin/env bash" >"$initfile"
if [ "$LAUNCH_TERMINAL_SHELL" != "bash" ]; then
    codefile="$(mktemp)"
    echo "$LAUNCH_TERMINAL_SHELL $codefile" >>"$initfile"
fi
echo "$1" >>"$codefile"
chmod +x "$initfile"
cmd="\"$initfile\""

terminal=""
declare -A terminals=(["alacritty"]="alacritty -e $cmd || LIBGL_ALWAYS_SOFTWARE=1 alacritty -e $cmd" ["konsole"]="konsole -e $cmd" ["kgx"]="kgx -e $cmd" ["gnome-terminal"]="gnome-terminal --wait -- $cmd" ["xfce4-terminal"]="xfce4-terminal --disable-server --command '$cmd'")