#!/bin/bash

# Check if pkexec exists and is executable
if command -v pkexec &>/dev/null; then
    # Use pkexec to run calamares with administrative privileges
    pkexec --disable-internal-agent /usr/bin/calamares "$@"
else
    # Fallback to running calamares without administrative privileges
    /usr/bin/calamares "$@"
fi
